### ISSUE TITLE
Allowing dev to load distant cobalt webview

### ISSUE THREAD

**Issue by ggendre** [cobaltians/Cobalt#135]
With current native implementation you can only load local pages, embedded in the app.

It could be fine to allow the user to put `page: "http://hisServer/dispage.html"` if he wants to use cobalt in it.

### todo

- [x] create a test page at http://cobaltians.org/test_distantCobaltView/index.html
- [x] create branche issue-135 on Cobalt-iOS
- [x] enable loading pages staring by http on Cobalt-iOS/issue-135
- [x] create branche issue-135 on Cobalt-Android
- [x] enable loading pages staring by http on Cobalt-Android/issue-135
- [ ] create branche issue-135 on Cobalt-Catalog-Web
- [ ] add exemple for distant webview loading in Cobalt-Catalog-Web
- [ ] create wiki documentation for this possibility
- [ ] write a blog article about this possibility
- [ ] merge branches to develop

**Comment by ggendre** [comment]
#135 #136 #137 all have their branche but are also merged into an experimental branche `issues-135-136-137` about weblayers fixes

**Comment by Doc1faux** [comment]
I approve this commit https://github.com/cobaltians/Cobalt-iOS/commit/da80dc197d009b7484d0c9ff97f527bfd48b1c46

**Comment by Doc1faux** [comment]
I approve this commit too https://github.com/cobaltians/Cobalt-Android/commit/544722a3878e7291dedc379e77c9a7e8bca1ab15

**Comment by Doc1faux** [comment]
Done in `weblayer-experiments` branches

**Comment by Doc1faux** [comment]
Reopen for example in Catalog, documentation & merge in develop ;)

**Comment by ggendre** [comment]
exemple done in cobalt catalogue
