### ISSUE TITLE
WebLayers bringToFront/sendToBack events

### ISSUE THREAD

**Issue by Doc1faux** [cobaltians/Cobalt#144]
We want to be able to bring the main WebView over the WebLayer and vice-versa, so here are new events to handle: 
- `{type: "webLayer", action: "bringToFront"}`
- `{type: "webLayer", action: "sendToBack"}`

**TODO:**
- [x] iOS: catch events
- [x] iOS: handle `bringToFront` event
- [x] iOS: handle `sendToBack` event
- [x] Android: catch events
- [x] Android: update WebLayer to not replace fragment to be able to do this
- [x] Android: handle `bringToFront` event
- [x] Android: handle `sendToBack` event
- [x] Web: add both events

**Comment by Doc1faux** [comment]
> update WebLayer to not replace fragment

Done by [this commit](https://github.com/cobaltians/Cobalt-Android/commit/705c6d9fef70b61f35d188bda7495a9f9162914a)

**Comment by ggendre** [comment]
- I added both events to cobalt.js on `develop` branch.
- I updated a bit the JS API to be more predictable (`cobalt.webLayer.show(page)` instead of `cobalt.webLayer('show', page)`)
- I updated the catalog to match this changes of API on `develop` branch
- I updated the wiki doc for these changes and for bringToFront sendToBack
- I created a `weblayer-experiments` branch on Samples-Catalog-Web, Samples-Catalog-iOS and Samples-Catalog-Android
- I used the good branch for cobalt, www/common and www/platform in those branches

**And I tested it** :
  - it works like a charm on iOS, big up ! 🎉 
  - it fails on Android : `sendToBack` is not working. weblayer disapears but main webview is locked. I tested sendToBack from the main webview and the weblayer with no better success. Once the weblayer is invisible, I tried `bringToFront` from the main webview or from the weblayer but it fails too.

**Comment by ggendre** [comment]
I saw this bug on Famicity : 

<img width="759" alt="capture d ecran 2017-07-25 a 09 58 49" src="https://user-images.githubusercontent.com/534697/28561779-f7d74026-711f-11e7-9a26-7ad52a3f161a.png">

probably a mis-usage of the web (bringing to front something that is not here yet) but I think we should fix it.

**Comment by ggendre** [comment]
not reproduced.
