### ISSUE TITLE
nativeBars - tint color on asset action

### ISSUE THREAD

**Issue by ggendre** [cobaltians/Cobalt#85]
### theory

when using an asset fo the project as an action icon, the `color` attribute of the action is applied as a tint on the png file.
Same rules is applied than for fonts : if no `color` on the item, use the bars `color`.

To reproduce, loads the Catalog nativeBars page and clic on "Completly change bars"  button. Icon should be same color as text.

### current status

**Doesn't work anymore on iOS**

<img width="460" alt="capture d ecran 2016-05-19 a 18 17 26" src="https://cloud.githubusercontent.com/assets/534697/15401306/357b3390-1def-11e6-974a-93cc1fd4267c.png">

**Doesn't work on Android**

<img width="319" alt="capture d ecran 2016-05-19 a 18 25 26" src="https://cloud.githubusercontent.com/assets/534697/15401319/4438d522-1def-11e6-8395-225f9110cc2a.png">

### TODO

- [x] add to documentation
- [x] update catalog app with a better color
- [x] fix it on iOS
- [x] make a screenshot on iOS and give it to ggendre (for the blog post)
- [x] **re**fix it on Android
- [x] make a screenshot on Android and give it to ggendre (for the blog post)
- [x] ggendre : write a quick blog post about this for later use.

**Comment by ggendre** [comment]
Here is what it looks like on iOS : the icon should be orange like the text : 
<img width="460" alt="capture d ecran 2016-05-19 a 18 17 26" src="https://cloud.githubusercontent.com/assets/534697/15401190/b4d02be2-1dee-11e6-85ce-ecd3460d3970.png">

**Comment by ggendre** [comment]
I updated the issue with more doc and screenshots. This doesn't work on both platforms 😢 .

**Comment by Doc1faux** [comment]
And here is your screenshot for iOS
![screen shot 2016-05-26 at 16 28 58](https://cloud.githubusercontent.com/assets/2175246/15578060/3ecd7ca8-235f-11e6-8dc0-0704479ce5e3.png)

**Comment by ggendre** [comment]
![tint_color_android](https://cloud.githubusercontent.com/assets/534697/15578677/c12d7796-2361-11e6-8fa1-2374e5b2d4f4.png)

**Comment by ggendre** [comment]
article done. closing :)
